//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace AltaCliente.WsDynamicsAx {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AxServiceProdSoap", Namespace="http://bepensa.net/")]
    public partial class AxServiceProd : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback altaCreditoOperationCompleted;
        
        private System.Threading.SendOrPostCallback altaClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback altaProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback altaLineaOperationCompleted;
        
        private System.Threading.SendOrPostCallback altaGarantiasOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertaComisionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertaGastosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getValTasaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTipoCambioOperationCompleted;
        
        private System.Threading.SendOrPostCallback contabilizaEventoOperationCompleted;
        
        private System.Threading.SendOrPostCallback altaOcOperationCompleted;
        
        private System.Threading.SendOrPostCallback altaPolizaOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateRefProsaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePropietarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback getImpProdReisntOperationCompleted;
        
        private System.Threading.SendOrPostCallback existVendAxOperationCompleted;
        
        private System.Threading.SendOrPostCallback existVendAx2OperationCompleted;
        
        private System.Threading.SendOrPostCallback asignaVendAxOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOpenPeriodoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTransAxFilOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTransAxFil2OperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateConfClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogonPruebaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AxServiceProd() {
            this.Url = global::AltaCliente.Properties.Settings.Default.AltaCliente_WsDynamicsAx_AxServiceProd;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event altaCreditoCompletedEventHandler altaCreditoCompleted;
        
        /// <remarks/>
        public event altaClienteCompletedEventHandler altaClienteCompleted;
        
        /// <remarks/>
        public event altaProductoCompletedEventHandler altaProductoCompleted;
        
        /// <remarks/>
        public event altaLineaCompletedEventHandler altaLineaCompleted;
        
        /// <remarks/>
        public event altaGarantiasCompletedEventHandler altaGarantiasCompleted;
        
        /// <remarks/>
        public event insertaComisionesCompletedEventHandler insertaComisionesCompleted;
        
        /// <remarks/>
        public event insertaGastosCompletedEventHandler insertaGastosCompleted;
        
        /// <remarks/>
        public event getValTasaCompletedEventHandler getValTasaCompleted;
        
        /// <remarks/>
        public event getTipoCambioCompletedEventHandler getTipoCambioCompleted;
        
        /// <remarks/>
        public event contabilizaEventoCompletedEventHandler contabilizaEventoCompleted;
        
        /// <remarks/>
        public event altaOcCompletedEventHandler altaOcCompleted;
        
        /// <remarks/>
        public event altaPolizaCompletedEventHandler altaPolizaCompleted;
        
        /// <remarks/>
        public event updateRefProsaCompletedEventHandler updateRefProsaCompleted;
        
        /// <remarks/>
        public event UpdatePropietarioCompletedEventHandler UpdatePropietarioCompleted;
        
        /// <remarks/>
        public event getImpProdReisntCompletedEventHandler getImpProdReisntCompleted;
        
        /// <remarks/>
        public event existVendAxCompletedEventHandler existVendAxCompleted;
        
        /// <remarks/>
        public event existVendAx2CompletedEventHandler existVendAx2Completed;
        
        /// <remarks/>
        public event asignaVendAxCompletedEventHandler asignaVendAxCompleted;
        
        /// <remarks/>
        public event getOpenPeriodoCompletedEventHandler getOpenPeriodoCompleted;
        
        /// <remarks/>
        public event getTransAxFilCompletedEventHandler getTransAxFilCompleted;
        
        /// <remarks/>
        public event getTransAxFil2CompletedEventHandler getTransAxFil2Completed;
        
        /// <remarks/>
        public event UpdateConfClienteCompletedEventHandler UpdateConfClienteCompleted;
        
        /// <remarks/>
        public event LogonPruebaCompletedEventHandler LogonPruebaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/altaCredito", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string altaCredito(string userdomain, string xmlSerializado, string calEventos, string calTasas, InfoConexion info) {
            object[] results = this.Invoke("altaCredito", new object[] {
                        userdomain,
                        xmlSerializado,
                        calEventos,
                        calTasas,
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void altaCreditoAsync(string userdomain, string xmlSerializado, string calEventos, string calTasas, InfoConexion info) {
            this.altaCreditoAsync(userdomain, xmlSerializado, calEventos, calTasas, info, null);
        }
        
        /// <remarks/>
        public void altaCreditoAsync(string userdomain, string xmlSerializado, string calEventos, string calTasas, InfoConexion info, object userState) {
            if ((this.altaCreditoOperationCompleted == null)) {
                this.altaCreditoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaltaCreditoOperationCompleted);
            }
            this.InvokeAsync("altaCredito", new object[] {
                        userdomain,
                        xmlSerializado,
                        calEventos,
                        calTasas,
                        info}, this.altaCreditoOperationCompleted, userState);
        }
        
        private void OnaltaCreditoOperationCompleted(object arg) {
            if ((this.altaCreditoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.altaCreditoCompleted(this, new altaCreditoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/altaCliente", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string altaCliente(string instancia, string xmlSerializado, InfoConexion info) {
            object[] results = this.Invoke("altaCliente", new object[] {
                        instancia,
                        xmlSerializado,
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void altaClienteAsync(string instancia, string xmlSerializado, InfoConexion info) {
            this.altaClienteAsync(instancia, xmlSerializado, info, null);
        }
        
        /// <remarks/>
        public void altaClienteAsync(string instancia, string xmlSerializado, InfoConexion info, object userState) {
            if ((this.altaClienteOperationCompleted == null)) {
                this.altaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaltaClienteOperationCompleted);
            }
            this.InvokeAsync("altaCliente", new object[] {
                        instancia,
                        xmlSerializado,
                        info}, this.altaClienteOperationCompleted, userState);
        }
        
        private void OnaltaClienteOperationCompleted(object arg) {
            if ((this.altaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.altaClienteCompleted(this, new altaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/altaProducto", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string altaProducto(string userdomian, string xmlSerializado) {
            object[] results = this.Invoke("altaProducto", new object[] {
                        userdomian,
                        xmlSerializado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void altaProductoAsync(string userdomian, string xmlSerializado) {
            this.altaProductoAsync(userdomian, xmlSerializado, null);
        }
        
        /// <remarks/>
        public void altaProductoAsync(string userdomian, string xmlSerializado, object userState) {
            if ((this.altaProductoOperationCompleted == null)) {
                this.altaProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaltaProductoOperationCompleted);
            }
            this.InvokeAsync("altaProducto", new object[] {
                        userdomian,
                        xmlSerializado}, this.altaProductoOperationCompleted, userState);
        }
        
        private void OnaltaProductoOperationCompleted(object arg) {
            if ((this.altaProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.altaProductoCompleted(this, new altaProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/altaLinea", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string altaLinea(string instancia, string xmlSerializado, InfoConexion info) {
            object[] results = this.Invoke("altaLinea", new object[] {
                        instancia,
                        xmlSerializado,
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void altaLineaAsync(string instancia, string xmlSerializado, InfoConexion info) {
            this.altaLineaAsync(instancia, xmlSerializado, info, null);
        }
        
        /// <remarks/>
        public void altaLineaAsync(string instancia, string xmlSerializado, InfoConexion info, object userState) {
            if ((this.altaLineaOperationCompleted == null)) {
                this.altaLineaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaltaLineaOperationCompleted);
            }
            this.InvokeAsync("altaLinea", new object[] {
                        instancia,
                        xmlSerializado,
                        info}, this.altaLineaOperationCompleted, userState);
        }
        
        private void OnaltaLineaOperationCompleted(object arg) {
            if ((this.altaLineaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.altaLineaCompleted(this, new altaLineaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/altaGarantias", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string altaGarantias(string instancia, string xmlSerializado, string xmlCal, InfoConexion info) {
            object[] results = this.Invoke("altaGarantias", new object[] {
                        instancia,
                        xmlSerializado,
                        xmlCal,
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void altaGarantiasAsync(string instancia, string xmlSerializado, string xmlCal, InfoConexion info) {
            this.altaGarantiasAsync(instancia, xmlSerializado, xmlCal, info, null);
        }
        
        /// <remarks/>
        public void altaGarantiasAsync(string instancia, string xmlSerializado, string xmlCal, InfoConexion info, object userState) {
            if ((this.altaGarantiasOperationCompleted == null)) {
                this.altaGarantiasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaltaGarantiasOperationCompleted);
            }
            this.InvokeAsync("altaGarantias", new object[] {
                        instancia,
                        xmlSerializado,
                        xmlCal,
                        info}, this.altaGarantiasOperationCompleted, userState);
        }
        
        private void OnaltaGarantiasOperationCompleted(object arg) {
            if ((this.altaGarantiasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.altaGarantiasCompleted(this, new altaGarantiasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/insertaComisiones", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insertaComisiones(string instancia, string xmlSerializado, InfoConexion info) {
            object[] results = this.Invoke("insertaComisiones", new object[] {
                        instancia,
                        xmlSerializado,
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertaComisionesAsync(string instancia, string xmlSerializado, InfoConexion info) {
            this.insertaComisionesAsync(instancia, xmlSerializado, info, null);
        }
        
        /// <remarks/>
        public void insertaComisionesAsync(string instancia, string xmlSerializado, InfoConexion info, object userState) {
            if ((this.insertaComisionesOperationCompleted == null)) {
                this.insertaComisionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertaComisionesOperationCompleted);
            }
            this.InvokeAsync("insertaComisiones", new object[] {
                        instancia,
                        xmlSerializado,
                        info}, this.insertaComisionesOperationCompleted, userState);
        }
        
        private void OninsertaComisionesOperationCompleted(object arg) {
            if ((this.insertaComisionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertaComisionesCompleted(this, new insertaComisionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/insertaGastos", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insertaGastos(string instancia, string xmlSerializado, InfoConexion info) {
            object[] results = this.Invoke("insertaGastos", new object[] {
                        instancia,
                        xmlSerializado,
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertaGastosAsync(string instancia, string xmlSerializado, InfoConexion info) {
            this.insertaGastosAsync(instancia, xmlSerializado, info, null);
        }
        
        /// <remarks/>
        public void insertaGastosAsync(string instancia, string xmlSerializado, InfoConexion info, object userState) {
            if ((this.insertaGastosOperationCompleted == null)) {
                this.insertaGastosOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertaGastosOperationCompleted);
            }
            this.InvokeAsync("insertaGastos", new object[] {
                        instancia,
                        xmlSerializado,
                        info}, this.insertaGastosOperationCompleted, userState);
        }
        
        private void OninsertaGastosOperationCompleted(object arg) {
            if ((this.insertaGastosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertaGastosCompleted(this, new insertaGastosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/getValTasa", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getValTasa(string instancia, string xmlSerializado) {
            object[] results = this.Invoke("getValTasa", new object[] {
                        instancia,
                        xmlSerializado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getValTasaAsync(string instancia, string xmlSerializado) {
            this.getValTasaAsync(instancia, xmlSerializado, null);
        }
        
        /// <remarks/>
        public void getValTasaAsync(string instancia, string xmlSerializado, object userState) {
            if ((this.getValTasaOperationCompleted == null)) {
                this.getValTasaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetValTasaOperationCompleted);
            }
            this.InvokeAsync("getValTasa", new object[] {
                        instancia,
                        xmlSerializado}, this.getValTasaOperationCompleted, userState);
        }
        
        private void OngetValTasaOperationCompleted(object arg) {
            if ((this.getValTasaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getValTasaCompleted(this, new getValTasaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/getTipoCambio", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTipoCambio(string instancia, string xmlSerializado) {
            object[] results = this.Invoke("getTipoCambio", new object[] {
                        instancia,
                        xmlSerializado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTipoCambioAsync(string instancia, string xmlSerializado) {
            this.getTipoCambioAsync(instancia, xmlSerializado, null);
        }
        
        /// <remarks/>
        public void getTipoCambioAsync(string instancia, string xmlSerializado, object userState) {
            if ((this.getTipoCambioOperationCompleted == null)) {
                this.getTipoCambioOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTipoCambioOperationCompleted);
            }
            this.InvokeAsync("getTipoCambio", new object[] {
                        instancia,
                        xmlSerializado}, this.getTipoCambioOperationCompleted, userState);
        }
        
        private void OngetTipoCambioOperationCompleted(object arg) {
            if ((this.getTipoCambioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTipoCambioCompleted(this, new getTipoCambioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/contabilizaEvento", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string contabilizaEvento(string instancia, string xmlSerializado, InfoConexion info) {
            object[] results = this.Invoke("contabilizaEvento", new object[] {
                        instancia,
                        xmlSerializado,
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void contabilizaEventoAsync(string instancia, string xmlSerializado, InfoConexion info) {
            this.contabilizaEventoAsync(instancia, xmlSerializado, info, null);
        }
        
        /// <remarks/>
        public void contabilizaEventoAsync(string instancia, string xmlSerializado, InfoConexion info, object userState) {
            if ((this.contabilizaEventoOperationCompleted == null)) {
                this.contabilizaEventoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontabilizaEventoOperationCompleted);
            }
            this.InvokeAsync("contabilizaEvento", new object[] {
                        instancia,
                        xmlSerializado,
                        info}, this.contabilizaEventoOperationCompleted, userState);
        }
        
        private void OncontabilizaEventoOperationCompleted(object arg) {
            if ((this.contabilizaEventoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.contabilizaEventoCompleted(this, new contabilizaEventoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/altaOc", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string altaOc(string user, string encabezado, string xml) {
            object[] results = this.Invoke("altaOc", new object[] {
                        user,
                        encabezado,
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void altaOcAsync(string user, string encabezado, string xml) {
            this.altaOcAsync(user, encabezado, xml, null);
        }
        
        /// <remarks/>
        public void altaOcAsync(string user, string encabezado, string xml, object userState) {
            if ((this.altaOcOperationCompleted == null)) {
                this.altaOcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaltaOcOperationCompleted);
            }
            this.InvokeAsync("altaOc", new object[] {
                        user,
                        encabezado,
                        xml}, this.altaOcOperationCompleted, userState);
        }
        
        private void OnaltaOcOperationCompleted(object arg) {
            if ((this.altaOcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.altaOcCompleted(this, new altaOcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/altaPoliza", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string altaPoliza(string user, string xml, string descrip) {
            object[] results = this.Invoke("altaPoliza", new object[] {
                        user,
                        xml,
                        descrip});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void altaPolizaAsync(string user, string xml, string descrip) {
            this.altaPolizaAsync(user, xml, descrip, null);
        }
        
        /// <remarks/>
        public void altaPolizaAsync(string user, string xml, string descrip, object userState) {
            if ((this.altaPolizaOperationCompleted == null)) {
                this.altaPolizaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaltaPolizaOperationCompleted);
            }
            this.InvokeAsync("altaPoliza", new object[] {
                        user,
                        xml,
                        descrip}, this.altaPolizaOperationCompleted, userState);
        }
        
        private void OnaltaPolizaOperationCompleted(object arg) {
            if ((this.altaPolizaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.altaPolizaCompleted(this, new altaPolizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/updateRefProsa", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateRefProsa(string user, string cvecred, string refprosa, string refbanacaria, InfoConexion info) {
            object[] results = this.Invoke("updateRefProsa", new object[] {
                        user,
                        cvecred,
                        refprosa,
                        refbanacaria,
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateRefProsaAsync(string user, string cvecred, string refprosa, string refbanacaria, InfoConexion info) {
            this.updateRefProsaAsync(user, cvecred, refprosa, refbanacaria, info, null);
        }
        
        /// <remarks/>
        public void updateRefProsaAsync(string user, string cvecred, string refprosa, string refbanacaria, InfoConexion info, object userState) {
            if ((this.updateRefProsaOperationCompleted == null)) {
                this.updateRefProsaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateRefProsaOperationCompleted);
            }
            this.InvokeAsync("updateRefProsa", new object[] {
                        user,
                        cvecred,
                        refprosa,
                        refbanacaria,
                        info}, this.updateRefProsaOperationCompleted, userState);
        }
        
        private void OnupdateRefProsaOperationCompleted(object arg) {
            if ((this.updateRefProsaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateRefProsaCompleted(this, new updateRefProsaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/UpdatePropietario", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdatePropietario(string creditoax, string propietario, InfoConexion info) {
            object[] results = this.Invoke("UpdatePropietario", new object[] {
                        creditoax,
                        propietario,
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePropietarioAsync(string creditoax, string propietario, InfoConexion info) {
            this.UpdatePropietarioAsync(creditoax, propietario, info, null);
        }
        
        /// <remarks/>
        public void UpdatePropietarioAsync(string creditoax, string propietario, InfoConexion info, object userState) {
            if ((this.UpdatePropietarioOperationCompleted == null)) {
                this.UpdatePropietarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePropietarioOperationCompleted);
            }
            this.InvokeAsync("UpdatePropietario", new object[] {
                        creditoax,
                        propietario,
                        info}, this.UpdatePropietarioOperationCompleted, userState);
        }
        
        private void OnUpdatePropietarioOperationCompleted(object arg) {
            if ((this.UpdatePropietarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePropietarioCompleted(this, new UpdatePropietarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/getImpProdReisnt", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getImpProdReisnt() {
            object[] results = this.Invoke("getImpProdReisnt", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getImpProdReisntAsync() {
            this.getImpProdReisntAsync(null);
        }
        
        /// <remarks/>
        public void getImpProdReisntAsync(object userState) {
            if ((this.getImpProdReisntOperationCompleted == null)) {
                this.getImpProdReisntOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetImpProdReisntOperationCompleted);
            }
            this.InvokeAsync("getImpProdReisnt", new object[0], this.getImpProdReisntOperationCompleted, userState);
        }
        
        private void OngetImpProdReisntOperationCompleted(object arg) {
            if ((this.getImpProdReisntCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getImpProdReisntCompleted(this, new getImpProdReisntCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/existVendAx", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string existVendAx(string alias) {
            object[] results = this.Invoke("existVendAx", new object[] {
                        alias});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void existVendAxAsync(string alias) {
            this.existVendAxAsync(alias, null);
        }
        
        /// <remarks/>
        public void existVendAxAsync(string alias, object userState) {
            if ((this.existVendAxOperationCompleted == null)) {
                this.existVendAxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexistVendAxOperationCompleted);
            }
            this.InvokeAsync("existVendAx", new object[] {
                        alias}, this.existVendAxOperationCompleted, userState);
        }
        
        private void OnexistVendAxOperationCompleted(object arg) {
            if ((this.existVendAxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.existVendAxCompleted(this, new existVendAxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/existVendAx2", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string existVendAx2(string user, string alias) {
            object[] results = this.Invoke("existVendAx2", new object[] {
                        user,
                        alias});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void existVendAx2Async(string user, string alias) {
            this.existVendAx2Async(user, alias, null);
        }
        
        /// <remarks/>
        public void existVendAx2Async(string user, string alias, object userState) {
            if ((this.existVendAx2OperationCompleted == null)) {
                this.existVendAx2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnexistVendAx2OperationCompleted);
            }
            this.InvokeAsync("existVendAx2", new object[] {
                        user,
                        alias}, this.existVendAx2OperationCompleted, userState);
        }
        
        private void OnexistVendAx2OperationCompleted(object arg) {
            if ((this.existVendAx2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.existVendAx2Completed(this, new existVendAx2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/asignaVendAx", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string asignaVendAx(string user, string vends) {
            object[] results = this.Invoke("asignaVendAx", new object[] {
                        user,
                        vends});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void asignaVendAxAsync(string user, string vends) {
            this.asignaVendAxAsync(user, vends, null);
        }
        
        /// <remarks/>
        public void asignaVendAxAsync(string user, string vends, object userState) {
            if ((this.asignaVendAxOperationCompleted == null)) {
                this.asignaVendAxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnasignaVendAxOperationCompleted);
            }
            this.InvokeAsync("asignaVendAx", new object[] {
                        user,
                        vends}, this.asignaVendAxOperationCompleted, userState);
        }
        
        private void OnasignaVendAxOperationCompleted(object arg) {
            if ((this.asignaVendAxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.asignaVendAxCompleted(this, new asignaVendAxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/getOpenPeriodo", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getOpenPeriodo() {
            object[] results = this.Invoke("getOpenPeriodo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getOpenPeriodoAsync() {
            this.getOpenPeriodoAsync(null);
        }
        
        /// <remarks/>
        public void getOpenPeriodoAsync(object userState) {
            if ((this.getOpenPeriodoOperationCompleted == null)) {
                this.getOpenPeriodoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOpenPeriodoOperationCompleted);
            }
            this.InvokeAsync("getOpenPeriodo", new object[0], this.getOpenPeriodoOperationCompleted, userState);
        }
        
        private void OngetOpenPeriodoOperationCompleted(object arg) {
            if ((this.getOpenPeriodoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOpenPeriodoCompleted(this, new getOpenPeriodoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/getTransAxFil", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTransAxFil(string user, string fecini, string fecfin) {
            object[] results = this.Invoke("getTransAxFil", new object[] {
                        user,
                        fecini,
                        fecfin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTransAxFilAsync(string user, string fecini, string fecfin) {
            this.getTransAxFilAsync(user, fecini, fecfin, null);
        }
        
        /// <remarks/>
        public void getTransAxFilAsync(string user, string fecini, string fecfin, object userState) {
            if ((this.getTransAxFilOperationCompleted == null)) {
                this.getTransAxFilOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTransAxFilOperationCompleted);
            }
            this.InvokeAsync("getTransAxFil", new object[] {
                        user,
                        fecini,
                        fecfin}, this.getTransAxFilOperationCompleted, userState);
        }
        
        private void OngetTransAxFilOperationCompleted(object arg) {
            if ((this.getTransAxFilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTransAxFilCompleted(this, new getTransAxFilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/getTransAxFil2", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTransAxFil2(string user, string empresa, string fecini, string fecfin) {
            object[] results = this.Invoke("getTransAxFil2", new object[] {
                        user,
                        empresa,
                        fecini,
                        fecfin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTransAxFil2Async(string user, string empresa, string fecini, string fecfin) {
            this.getTransAxFil2Async(user, empresa, fecini, fecfin, null);
        }
        
        /// <remarks/>
        public void getTransAxFil2Async(string user, string empresa, string fecini, string fecfin, object userState) {
            if ((this.getTransAxFil2OperationCompleted == null)) {
                this.getTransAxFil2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTransAxFil2OperationCompleted);
            }
            this.InvokeAsync("getTransAxFil2", new object[] {
                        user,
                        empresa,
                        fecini,
                        fecfin}, this.getTransAxFil2OperationCompleted, userState);
        }
        
        private void OngetTransAxFil2OperationCompleted(object arg) {
            if ((this.getTransAxFil2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTransAxFil2Completed(this, new getTransAxFil2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/UpdateConfCliente", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateConfCliente(string xmlSerializado, InfoConexion info) {
            object[] results = this.Invoke("UpdateConfCliente", new object[] {
                        xmlSerializado,
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateConfClienteAsync(string xmlSerializado, InfoConexion info) {
            this.UpdateConfClienteAsync(xmlSerializado, info, null);
        }
        
        /// <remarks/>
        public void UpdateConfClienteAsync(string xmlSerializado, InfoConexion info, object userState) {
            if ((this.UpdateConfClienteOperationCompleted == null)) {
                this.UpdateConfClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateConfClienteOperationCompleted);
            }
            this.InvokeAsync("UpdateConfCliente", new object[] {
                        xmlSerializado,
                        info}, this.UpdateConfClienteOperationCompleted, userState);
        }
        
        private void OnUpdateConfClienteOperationCompleted(object arg) {
            if ((this.UpdateConfClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateConfClienteCompleted(this, new UpdateConfClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bepensa.net/LogonPrueba", RequestNamespace="http://bepensa.net/", ResponseNamespace="http://bepensa.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LogonPrueba(string u, string d, string e, string s) {
            this.Invoke("LogonPrueba", new object[] {
                        u,
                        d,
                        e,
                        s});
        }
        
        /// <remarks/>
        public void LogonPruebaAsync(string u, string d, string e, string s) {
            this.LogonPruebaAsync(u, d, e, s, null);
        }
        
        /// <remarks/>
        public void LogonPruebaAsync(string u, string d, string e, string s, object userState) {
            if ((this.LogonPruebaOperationCompleted == null)) {
                this.LogonPruebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogonPruebaOperationCompleted);
            }
            this.InvokeAsync("LogonPrueba", new object[] {
                        u,
                        d,
                        e,
                        s}, this.LogonPruebaOperationCompleted, userState);
        }
        
        private void OnLogonPruebaOperationCompleted(object arg) {
            if ((this.LogonPruebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogonPruebaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bepensa.net/")]
    public partial class InfoConexion {
        
        private string usuarioField;
        
        private string dominioField;
        
        private string empresaField;
        
        private string servidorField;
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string dominio {
            get {
                return this.dominioField;
            }
            set {
                this.dominioField = value;
            }
        }
        
        /// <remarks/>
        public string empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        public string servidor {
            get {
                return this.servidorField;
            }
            set {
                this.servidorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void altaCreditoCompletedEventHandler(object sender, altaCreditoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class altaCreditoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal altaCreditoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void altaClienteCompletedEventHandler(object sender, altaClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class altaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal altaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void altaProductoCompletedEventHandler(object sender, altaProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class altaProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal altaProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void altaLineaCompletedEventHandler(object sender, altaLineaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class altaLineaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal altaLineaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void altaGarantiasCompletedEventHandler(object sender, altaGarantiasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class altaGarantiasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal altaGarantiasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void insertaComisionesCompletedEventHandler(object sender, insertaComisionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertaComisionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertaComisionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void insertaGastosCompletedEventHandler(object sender, insertaGastosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertaGastosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertaGastosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getValTasaCompletedEventHandler(object sender, getValTasaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getValTasaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getValTasaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getTipoCambioCompletedEventHandler(object sender, getTipoCambioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTipoCambioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTipoCambioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void contabilizaEventoCompletedEventHandler(object sender, contabilizaEventoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class contabilizaEventoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal contabilizaEventoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void altaOcCompletedEventHandler(object sender, altaOcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class altaOcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal altaOcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void altaPolizaCompletedEventHandler(object sender, altaPolizaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class altaPolizaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal altaPolizaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void updateRefProsaCompletedEventHandler(object sender, updateRefProsaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateRefProsaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateRefProsaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdatePropietarioCompletedEventHandler(object sender, UpdatePropietarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePropietarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePropietarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getImpProdReisntCompletedEventHandler(object sender, getImpProdReisntCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getImpProdReisntCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getImpProdReisntCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void existVendAxCompletedEventHandler(object sender, existVendAxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class existVendAxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal existVendAxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void existVendAx2CompletedEventHandler(object sender, existVendAx2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class existVendAx2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal existVendAx2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void asignaVendAxCompletedEventHandler(object sender, asignaVendAxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class asignaVendAxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal asignaVendAxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getOpenPeriodoCompletedEventHandler(object sender, getOpenPeriodoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOpenPeriodoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOpenPeriodoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getTransAxFilCompletedEventHandler(object sender, getTransAxFilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTransAxFilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTransAxFilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getTransAxFil2CompletedEventHandler(object sender, getTransAxFil2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTransAxFil2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTransAxFil2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateConfClienteCompletedEventHandler(object sender, UpdateConfClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateConfClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateConfClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LogonPruebaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591